name: CI Build

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Dockerfile'
      - 'src/entrypoint.sh'
      - 'upstream_latest_release.txt'
      - 'upstream_docker_version.txt'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version number
        id: version
        run: |
          echo "VERSION=$(cat upstream_latest_release.txt)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cmsj/imap-backup:latest
            ghcr.io/cmsj/imap-backup:${{ steps.version.outputs.VERSION }}
