name: Get latest release version
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 05 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch release version
        run: |
          curl -sL https://api.rubygems.org/api/v1/versions/imap-backup.json | jq -r '.[0] | .number' >upstream_latest_release.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Robot Jones'
          git config --global user.email 'cmsj@tenshu.net'
          git commit -am "New upstream release"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

